###
# fastq2bam workflow
##

# fastq download
get_fastq_pe:
    threads: 10
    mem: 2000
# compress fastq
gzip_fastq:
    mem: 4000
# fastp program
fastp: 
    threads: 10 
    mem: 5000
# index reference
index_ref:
    mem: 10000
# genmap map
genmap:
    threads: 10
# bwa mapping
bwa_map: 
    threads: 10 
    mem: 10000
# sort bam with picard's SortSam tool
sort_bam: 
    mem: 10000 
# mark duplicates with picard's MarkDuplicates
dedup: 
    mem: 9000 
# calculate BAM summaries with samtools and picard
bam_sumstats: 
    mem: 9000 
merge_bams:
    mem: 9000

###
# Intervals workflow
###

# preprocess genome, create intervals
# picard's create CreateSequenceDictionary, samtools faidx
process_ref:
    mem: 10000
# custom python algo to create intervals
create_intervals:
    mem: 5000

###
# bam2vcf workflows
###

# gatk HaplotypeCaller
bam2gvcf: 
    mem: 10000
# gatk GenomicsDBImport
gvcf2DB:
    mem: 10000
# gatk GenotypeGVCFs 
DB2vcf: 
    mem: 10000
## freebayes program only! ##
bam2vcf:
    mem: 10000
# gatk filterVcfs
filterVcfs:
    mem: 10000
# gatk GatherVcfs
gatherVcfs:
    mem: 10000
# picard SortVcf
sortVcf:
    mem: 10000
# vcftools program
vcftools:
    mem: 10000
# bedtools program
bedtools:
    mem: 10000
# plink
plink:
    threads: 5