##############################
# Variables you need to change
##############################

ref: "/n/holylfs/LABS/informatics/alex_lg/cod-pop-gen/00_input_data/REFs/Gardmor3.fasta"    # location of the reference genome

# If using the fastq -> BAM workflow change these, otherwise ignore them
fastqDir: "data/BHduck/fastq/"      # location of fastq files; must be followed by a "/"
fastq_suffix1: "_1.fastq.gz"            # the suffix for the forward reads that follows all the sample names, e.g. "_1.fastq.gz" for sample "sampleName_1.fastq.gz"
fastq_suffix2: "_2.fastq.gz"            # the suffix for the reverse reads that follows all the sample names, e.g. "_2.fastq.gz" for sample "sampleName_2.fastq.gz"


##############################
# Variables you *might* need to change
##############################

# if using the BAM -> VCF workflows
bamsForGatk: "/n/holylfs/LABS/informatics/alex_lg/cod-pop-gen/00_input_data/BAMs/Agl/" # directory containing BAMs for GATK. If you used the fastq -> bam workflow above, simply keep the default value; must be followed by a "/"
bamsForFB: "fastq2bam/01_mappedReads/"   # directory containing BAMs for Freebayes. If you used the fastq -> bam workflow above, simply keep the default value; must be followed by a "/"
bam_suffix: ".dedup.sorted.bam"                 # the suffix for your BAM files that follow all the sample names. If you use the fastq->BAM workflow above, simply keep the default value 

# These parameters control how the genome gets split into intervals according to Nmers in the reference genome
minNmer: 500                    # the minimum Nmer used to split up the genome; e.g. a value of 200 means only Nmers 200 or greater are used to define the boundaries of intervals. The minimum is 50.
maxIntervalLen: 15000000          # the desired maximum size of an interval for calling variants; more than 2Mb is a good starting point
maxBpPerList: 15000000            # the desired maximum number of bp per list file for GATK4; list files potentially contain many small intervals, and we cap the fraction of the genome contained in each list file here
maxIntervalsPerList: 200        # the desired maximum number of intervals per list file for GATK4; this prevents list files from containing thousands of small intervals, which can slow parts of GATK4. Default is good.

maxDP_fb: 200 # this is the maximum depth parameter used for freebayes, site with more than this number are ignored, change according to expected depth

##############################
# Variables you DO NOT need to change
# if you do, ensure all path/directory names are followed by a "/"
##############################

# These variables control the output of the fastq2bam workflow. You don't need to change these, but if you do please have a forward slash follow name!
fastq2bamDir: "fastq2bam/"              # this is the name of the directory for all the output
fastqFilterDir: "00_fastqFiltered/"     # new directory created for filtered fastq reads
bamDir: "01_mappedReads/"               # new directory created for BAM files
sumstatDir: "02_bamSumstats/"           # new directory created for BAM summary statistics

# These variables control the output of the GATK4 workflow (please have forward slash follow name!)
gatkDir: "gatk/"
gvcfDir: "01_gvcfs/"
dbDir: "02_genomicsDB/"
vcfDir_gatk: "03_vcfs/"
intDir: "intervalFiles/"

# These variables control the output of the FreeBayes workflow (please have forward slash follow name!)   
fbDir: "freebayes/"
intervalDir: "00_intervals/"
vcfDir_fb: "01_vcfs_byinterval/"

#information for read groups
flowcell: "FLOWCELL"
platform: "ILLUMINA"

cluster_config: "profiles/slurm/cluster_config.yml"

