##############################
# Variables you need to change
##############################

samples: "config/samples.csv" # path to the sample metadata CSV
final_prefix: "" # prefix for final output files



